## Base settings ##
url: https://www.mss866.top #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: 陌上桑的博客
description: >


nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

paths:
  base: /
  home: https://chen866.github.io
  # all:  /all.html
  # rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: chen866/chen866.github.io
repository_tree: master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: 陌上桑
  email: 1617383757@qq.com  #your Email address e.g. someone@site.com
  #facebook: someone  #your Facebook username
  #twitter: someone  #your Twitter username
  #github: someone  #your GitHub username
  #googleplus: someone  #your Google+ username
  #weibo: someone  #your Weibo username
  #douban: someone  #your Douban username
  #linkedin: someone  #your Linkedin username

## Comment system (Disqus) ##
  # shortname:  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true

## Paginate ##
paginate: 10
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  # - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false